### ISSUE TITLE
Version information - hardcoded

### ISSUE THREAD

**Issue by Allunatik** [playmer/ONScripter-EN-Official#10]
Currently the version information is hardcoded and it'd be good to have it tied to "versionstr"

![image](https://github.com/playmer/ONScripter-EN-Official/assets/142026488/d4eccba7-baef-4fbe-ab86-c4c4e1bd4f29)

API
-
https://kaisernet.org/onscripter/api/NScrAPI.html#versionstr

**Comment by playmer** [comment]
Just checked into the emscripten branch
