### ISSUE TITLE
Certain audio formats don't seem to work

### ISSUE THREAD

**Issue by Allunatik** [playmer/ONScripter-EN-Official#2]
.MP3
.MID

Confirmed to work on
https://github.com/Galladite27/ONScripter-EN/releases/tag/2023-06-28

command to execute doesn't seem to matter:
wave, bgm, bgmonce, loopbgm

Tested game: NETANNAD
Only splash music plays, menu music does not and neither SFX in game

**Comment by playmer** [comment]
I'm working on getting them both to work. Examining the current script for Netannad, it seems like it's using the `play` command, which indeed wouldn't work for directly playing either of these file types. Changing it to bgm though still produces issues. Not sure why, but I've had issues getting smpeg2 to output MP3. I've been meaning to switch to using SDL_Mixer for MP3 (and other) codec handling, so I'm currently working on switching over. As I was writing that sentence my build finish and I just got the MP3 audio to work lol. I'll see if I can get the midis to work as well.

Midi works in the original repos version? That's surprising, I haven't noticed what dependency that's leaning on for that.

Edit: Correction, I think `play` _should_ work for midi files. Unsure if bgm should.

**Comment by playmer** [comment]
Okay, so looked into the commands a bit more and yeah I think `play` is the right command for midi (although bgm also works, it's possible others do as well). Similarly for mp3 the command should be `bgm` or similar for mp3s.

Now that said, I expect play _would_ work, if set up to pretend you're looking at a CD, similar to how Tsukihime has their music set up, as play has a fall back to that. 

It's possible there are still issues here, but I've enabled midi and mp3, and added a default soundfont to usethat seems to be licensed in a friendly way for gpl projects (https://www.schristiancollins.com/generaluser.php). In theory I can set it up to allow multiple fonts or something. But for now I think it's correct.
