### ISSUE TITLE
Auto mode

### ISSUE THREAD

**Issue by Allunatik** [playmer/ONScripter-EN-Official#4]
Auto mode doesn't seem to trigger even if nscript has automode_time defined

I.e NETANNAD
```
numalias auto_speed,999
automode_time %auto_speed
```
Tested games:
NETANNAD, Tsukihime

Behavior:
Nothing happens when clicking auto mode

Intended behavior:
Text advances by itself at intervals, auto mode is interrupted if player clicks the game window

API
https://kaisernet.org/onscripter/api/NScrAPI.html#automode
https://kaisernet.org/onscripter/api/NScrAPI.html#automode_time

Note:
Could add a default value if script doesn't have automode_time set to support it in other titles by default

**Comment by playmer** [comment]
Fixed this in the emscripten-kitchensink branch. Audio is being worked on there (although I don't _think_ anything is actually broken currently), but this should work fine for your Tsukhime-Trial needs, let me know when you want a build.
