### ISSUE TITLE
Font selection

### ISSUE THREAD

**Issue by Allunatik** [playmer/ONScripter-EN-Official#5]
Font selection doesn't have a submenu - options
-

![image](https://github.com/playmer/ONScripter-EN-Official/assets/142026488/8265b2ba-4937-411a-b620-ebbf909431fa)

Rough TL (Can ask to be checked for accuracy if can't be pulled from system..)
Note: don't think these need to be translated apart from "Default"

Behavior:
-

Intended behavior:
-
Hovering over the menu item shows a submenu of fonts > choice changes the displayed font ingame on next window

MS Gothic
NSimSun
SimSun-ExtB
BIZ UD Gothic
Biz UD Ming Dynasty Medium
MS Ming Dynasty
UD Digital Textbook N-B
UD Digital Textbook N-R
Ripple Gothic
Default

API
https://kaisernet.org/onscripter/api/NScrAPI.html#font (Seems to be the one's used by insertmenu - menu bar)
Relevant:
https://kaisernet.org/onscripter/api/NScrAPI.html#defaultfont

**Comment by playmer** [comment]
Looks like runtime font changing isn't a thing in onscripter, but I should be able to relatively easily fix the the menu to change the font at restart. I'll look into runtime font changing though, but no immediate promises.

**Comment by Allunatik** [comment]
No worries let me know if you need additional information - translations

**Comment by playmer** [comment]
Closed earlier this week! (unrelated to the above commit, that's fixing an upstream issue)
