### ISSUE TITLE
Input dialog doesn't launch

### ISSUE THREAD

**Issue by Allunatik** [playmer/ONScripter-EN-Official#8]
Input dialogs in NETANNAD won't launch

Behavior:

Intended behavior:
Start game >Is your name .. >input for inserting character name appears

Script
-
```
inputstr $2,`Enter your first name. (Up to 4 full-width characters)`,16,1
inputstr $1,`Enter your last name. (Up to 4 full-width characters)`,16,1
```

API
-
https://kaisernet.org/onscripter/api/NScrAPI.html#inputstr
Relevant similar window:
https://kaisernet.org/onscripter/api/NScrAPI.html#inputnum
Other dialogs see (not used in NETANNAD, but might want to support) (yes, no etc):
https://kaisernet.org/onscripter/api/NScrAPI.html#category_additional

**Comment by playmer** [comment]
Checked in a fix in the emscripten branch.
