### ISSUE TITLE
Offcentered dialogs

### ISSUE THREAD

**Issue by Allunatik** [playmer/ONScripter-EN-Official#9]
Small issue but i noticed some Offcentered dialogs compared to the volume mixer

- Exit (Actually Nscripter launches this in the center of the display not the game window, but i think the game window is more desirable)
- version information

**Comment by playmer** [comment]
Just to be clear, the ideal here is to be placed in the center of the window for all dialogs?  I think I can make that work.

**Comment by playmer** [comment]
Checked in a fix to emscripten branch.

In theory if these compile you can download versions from each commit on the associated action page, here's the one for that commit: https://github.com/playmer/ONScripter-EN-Official/actions/runs/6256480994

(But I also understand wanting to wait until I fix more of them, just letting you know :) )
